/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AutonomiaRouteImport } from './routes/autonomia'
import { Route as OfferteRouteImport } from './routes/offerte'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutonomiaRoute = AutonomiaRouteImport.update({
  id: '/autonomia',
  path: '/autonomia',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferteRoute = OfferteRouteImport.update({
  id: '/offerte',
  path: '/offerte',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/autonomia': typeof AutonomiaRoute
  '/offerte': typeof OfferteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/autonomia': typeof AutonomiaRoute
  '/offerte': typeof OfferteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/autonomia': typeof AutonomiaRoute
  '/offerte': typeof OfferteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/autonomia' | '/offerte'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/autonomia' | '/offerte'
  id: '__root__' | '/' | '/autonomia' | '/offerte'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutonomiaRoute: typeof AutonomiaRoute
  OfferteRoute: typeof OfferteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autonomia': {
      id: '/autonomia'
      path: '/autonomia'
      fullPath: '/autonomia'
      preLoaderRoute: typeof AutonomiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offerte': {
      id: '/offerte'
      path: '/offerte'
      fullPath: '/offerte'
      preLoaderRoute: typeof OfferteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutonomiaRoute: AutonomiaRoute,
  OfferteRoute: OfferteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
